name: Deploy to AWS
run-name: ${{ github.actor }} started a deployment
on:
  push:
    branches: [ master ]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::658680537871:user/github-actions
          aws-region: eu-central-1
      - name: run deploy script
        run: ./scripts/deploy.sh